/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PostularRouteImport } from './routes/postular'
import { Route as IndexRouteImport } from './routes/index'

const PostularRoute = PostularRouteImport.update({
  id: '/postular',
  path: '/postular',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/postular': typeof PostularRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/postular': typeof PostularRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/postular': typeof PostularRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/postular'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/postular'
  id: '__root__' | '/' | '/postular'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostularRoute: typeof PostularRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/postular': {
      id: '/postular'
      path: '/postular'
      fullPath: '/postular'
      preLoaderRoute: typeof PostularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostularRoute: PostularRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
