/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniversidadesRouteImport } from './routes/universidades'
import { Route as PostularRouteImport } from './routes/postular'
import { Route as ExperienciasRouteImport } from './routes/experiencias'
import { Route as ComunidadRouteImport } from './routes/comunidad'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'

const UniversidadesRoute = UniversidadesRouteImport.update({
  id: '/universidades',
  path: '/universidades',
  getParentRoute: () => rootRouteImport,
} as any)
const PostularRoute = PostularRouteImport.update({
  id: '/postular',
  path: '/postular',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciasRoute = ExperienciasRouteImport.update({
  id: '/experiencias',
  path: '/experiencias',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadRoute = ComunidadRouteImport.update({
  id: '/comunidad',
  path: '/comunidad',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/comunidad': typeof ComunidadRoute
  '/experiencias': typeof ExperienciasRoute
  '/postular': typeof PostularRoute
  '/universidades': typeof UniversidadesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/comunidad': typeof ComunidadRoute
  '/experiencias': typeof ExperienciasRoute
  '/postular': typeof PostularRoute
  '/universidades': typeof UniversidadesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/comunidad': typeof ComunidadRoute
  '/experiencias': typeof ExperienciasRoute
  '/postular': typeof PostularRoute
  '/universidades': typeof UniversidadesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/comunidad'
    | '/experiencias'
    | '/postular'
    | '/universidades'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/comunidad'
    | '/experiencias'
    | '/postular'
    | '/universidades'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/comunidad'
    | '/experiencias'
    | '/postular'
    | '/universidades'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  ComunidadRoute: typeof ComunidadRoute
  ExperienciasRoute: typeof ExperienciasRoute
  PostularRoute: typeof PostularRoute
  UniversidadesRoute: typeof UniversidadesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/universidades': {
      id: '/universidades'
      path: '/universidades'
      fullPath: '/universidades'
      preLoaderRoute: typeof UniversidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postular': {
      id: '/postular'
      path: '/postular'
      fullPath: '/postular'
      preLoaderRoute: typeof PostularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencias': {
      id: '/experiencias'
      path: '/experiencias'
      fullPath: '/experiencias'
      preLoaderRoute: typeof ExperienciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidad': {
      id: '/comunidad'
      path: '/comunidad'
      fullPath: '/comunidad'
      preLoaderRoute: typeof ComunidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  ComunidadRoute: ComunidadRoute,
  ExperienciasRoute: ExperienciasRoute,
  PostularRoute: PostularRoute,
  UniversidadesRoute: UniversidadesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
